// ===========================
// LetterCraft AI - Colorful Theme Engine
// ===========================

const THEMES = {
    default: {
        name: 'Modern Blue',
        color: '#3b82f6',
        colorLight: '#dbeafe',
        colorDark: '#1e40af',
        headerBg: '#f8fafc',
        headerColor: '#1e293b',
        border: '#e2e8f0',
        accent: '#3b82f6',
        watermark: '',
        gradient: 'from-blue-50 to-white',
        buttonBg: '#3b82f6',
        buttonHover: '#2563eb',
        previewHeader: 'linear-gradient(90deg, #3b82f6, #60a5fa)',
    },
    indigo: {
        name: 'Indigo Elegance',
        color: '#6366f1',
        colorLight: '#e0e7ff',
        colorDark: '#3730a3',
        headerBg: '#eef2ff',
        headerColor: '#312e81',
        border: '#c7d2fe',
        accent: '#6366f1',
        watermark: '',
        gradient: 'from-indigo-50 to-white',
        buttonBg: '#6366f1',
        buttonHover: '#4f46e5',
        previewHeader: 'linear-gradient(90deg, #6366f1, #818cf8)',
    },
    government: {
        name: 'Government Official',
        color: '#1e3a8a',
        colorLight: '#dbeafe',
        colorDark: '#172554',
        headerBg: '#1e3a8a',
        headerColor: '#ffffff',
        border: '#1e40af',
        accent: '#1e3a8a',
        watermark: 'OFFICIAL',
        gradient: 'from-blue-900 to-blue-800',
        buttonBg: '#1e3a8a',
        buttonHover: '#172554',
        previewHeader: 'linear-gradient(90deg, #1e3a8a, #1e40af)',
    },
    corporate: {
        name: 'Corporate Slate',
        color: '#0f172a',
        colorLight: '#f1f5f9',
        colorDark: '#020617',
        headerBg: '#0f172a',
        headerColor: '#ffffff',
        border: '#334155',
        accent: '#64748b',
        watermark: '',
        gradient: 'from-slate-800 to-slate-900',
        buttonBg: '#334155',
        buttonHover: '#1e293b',
        previewHeader: 'linear-gradient(90deg, #0f172a, #334155)',
    },
    medical: {
        name: 'Medical Green',
        color: '#059669',
        colorLight: '#d1fae5',
        colorDark: '#064e3b',
        headerBg: '#ecfdf5',
        headerColor: '#064e3b',
        border: '#34d399',
        accent: '#10b981',
        watermark: '',
        gradient: 'from-emerald-50 to-white',
        buttonBg: '#059669',
        buttonHover: '#047857',
        previewHeader: 'linear-gradient(90deg, #059669, #10b981)',
    },
    school: {
        name: 'School Amber',
        color: '#d97706',
        colorLight: '#fef3c7',
        colorDark: '#92400e',
        headerBg: '#fffbeb',
        headerColor: '#92400e',
        border: '#f59e0b',
        accent: '#f59e0b',
        watermark: '',
        gradient: 'from-amber-50 to-white',
        buttonBg: '#d97706',
        buttonHover: '#b45309',
        previewHeader: 'linear-gradient(90deg, #d97706, #f59e0b)',
    },
    legal: {
        name: 'Legal Maroon',
        color: '#7c2d12',
        colorLight: '#fef2f2',
        colorDark: '#450a0a',
        headerBg: '#fef2f2',
        headerColor: '#7c2d12',
        border: '#b91c1c',
        accent: '#dc2626',
        watermark: 'LEGAL',
        gradient: 'from-red-50 to-white',
        buttonBg: '#7c2d12',
        buttonHover: '#631c06',
        previewHeader: 'linear-gradient(90deg, #7c2d12, #b91c1c)',
    },
    personal: {
        name: 'Rose Personal',
        color: '#db2777',
        colorLight: '#fce7f3',
        colorDark: '#831843',
        headerBg: '#fdf2f8',
        headerColor: '#831843',
        border: '#f472b6',
        accent: '#ec4899',
        watermark: '',
        gradient: 'from-pink-50 to-white',
        buttonBg: '#db2777',
        buttonHover: '#be185d',
        previewHeader: 'linear-gradient(90deg, #db2777, #ec4899)',
    },
    teal: {
        name: 'Teal Fresh',
        color: '#0d9488',
        colorLight: '#ccfbf1',
        colorDark: '#134e4a',
        headerBg: '#f0fdfa',
        headerColor: '#134e4a',
        border: '#14b8a6',
        accent: '#2dd4bf',
        watermark: '',
        gradient: 'from-teal-50 to-white',
        buttonBg: '#0d9488',
        buttonHover: '#0f766e',
        previewHeader: 'linear-gradient(90deg, #0d9488, #14b8a6)',
    },
    purple: {
        name: 'Royal Purple',
        color: '#7c3aed',
        colorLight: '#ede9fe',
        colorDark: '#5b21b6',
        headerBg: '#f5f3ff',
        headerColor: '#5b21b6',
        border: '#8b5cf6',
        accent: '#a78bfa',
        watermark: '',
        gradient: 'from-violet-50 to-white',
        buttonBg: '#7c3aed',
        buttonHover: '#6d28d9',
        previewHeader: 'linear-gradient(90deg, #7c3aed, #8b5cf6)',
    },
    minimal: {
        name: 'Minimal Clean',
        color: '#475569',
        colorLight: '#f8fafc',
        colorDark: '#0f172a',
        headerBg: '#ffffff',
        headerColor: '#334155',
        border: '#94a3b8',
        accent: '#64748b',
        watermark: '',
        gradient: 'from-slate-50 to-white',
        buttonBg: '#475569',
        buttonHover: '#334155',
        previewHeader: 'linear-gradient(90deg, #475569, #64748b)',
    },
    nature: {
        name: 'Nature Green',
        color: '#16a34a',
        colorLight: '#dcfce7',
        colorDark: '#14532d',
        headerBg: '#f0fdf4',
        headerColor: '#14532d',
        border: '#4ade80',
        accent: '#22c55e',
        watermark: '',
        gradient: 'from-green-50 to-white',
        buttonBg: '#16a34a',
        buttonHover: '#15803d',
        previewHeader: 'linear-gradient(90deg, #16a34a, #22c55e)',
    },
    ocean: {
        name: 'Ocean Blue',
        color: '#0284c7',
        colorLight: '#e0f2fe',
        colorDark: '#0c4a6e',
        headerBg: '#f0f9ff',
        headerColor: '#0c4a6e',
        border: '#38bdf8',
        accent: '#0ea5e9',
        watermark: '',
        gradient: 'from-sky-50 to-white',
        buttonBg: '#0284c7',
        buttonHover: '#0369a1',
        previewHeader: 'linear-gradient(90deg, #0284c7, #0ea5e9)',
    },
    sunset: {
        name: 'Sunset Orange',
        color: '#ea580c',
        colorLight: '#ffedd5',
        colorDark: '#7c2d12',
        headerBg: '#fff7ed',
        headerColor: '#7c2d12',
        border: '#fb923c',
        accent: '#f97316',
        watermark: '',
        gradient: 'from-orange-50 to-white',
        buttonBg: '#ea580c',
        buttonHover: '#c2410c',
        previewHeader: 'linear-gradient(90deg, #ea580c, #f97316)',
    },
    dark: {
        name: 'Dark Mode',
        color: '#1e293b',
        colorLight: '#334155',
        colorDark: '#020617',
        headerBg: '#1e293b',
        headerColor: '#f8fafc',
        border: '#475569',
        accent: '#94a3b8',
        watermark: '',
        gradient: 'from-slate-800 to-slate-900',
        buttonBg: '#1e293b',
        buttonHover: '#0f172a',
        previewHeader: 'linear-gradient(90deg, #1e293b, #334155)',
    },
    festival: {
        name: 'Festival Red',
        color: '#b91c1c',
        colorLight: '#fef2f2',
        colorDark: '#7f1d1d',
        headerBg: '#fef2f2',
        headerColor: '#7f1d1d',
        border: '#ef4444',
        accent: '#f87171',
        watermark: '',
        gradient: 'from-red-50 to-white',
        buttonBg: '#b91c1c',
        buttonHover: '#991b1b',
        previewHeader: 'linear-gradient(90deg, #b91c1c, #ef4444)',
    },
};

function getTheme(key) {
    return THEMES[key] || THEMES.default;
}

function renderThemeGrid(container, currentTheme, onSelect) {
    const grid = document.getElementById(container) || document.getElementById('themeGrid');
    if (!grid) return;
    grid.innerHTML = Object.entries(THEMES).map(([key, t]) => `
        <div class="theme-card ${currentTheme === key ? 'active' : ''}" onclick="selectTheme('${key}')" data-theme="${key}">
            <div class="flex items-center gap-2">
                <div class="w-5 h-5 rounded-full shadow-sm" style="background:${t.color}"></div>
                <span class="text-xs font-semibold text-slate-700">${t.name}</span>
            </div>
            <div class="mt-1.5 h-1.5 rounded-full" style="background:${t.color};opacity:0.25"></div>
        </div>
    `).join('');
}

function getThemeStyles(themeKey) {
    const t = getTheme(themeKey);
    return {
        headerBar: `background: ${t.previewHeader}; height: 5px; border-radius: 3px; margin-bottom: 18px;`,
        watermark: t.watermark ? `<div class="preview-watermark" style="color:${t.color};opacity:0.04">${t.watermark}</div>` : '',
        headerText: (text) => text ? `<div style="font-size:11px;color:${t.color};font-weight:700;text-align:center;margin-bottom:10px;text-transform:uppercase;letter-spacing:1.5px;border-bottom:2px solid ${t.colorLight};padding-bottom:8px;">${text}</div>` : '',
        footerText: (text) => text ? `<div style="font-size:9px;color:#64748b;text-align:center;margin-top:16px;border-top:1px solid ${t.border};padding-top:10px;">${text}</div>` : '',
        accentColor: t.color,
        borderColor: t.border,
    };
}

window.THEMES = THEMES;
window.getTheme = getTheme;
window.renderThemeGrid = renderThemeGrid;
window.getThemeStyles = getThemeStyles;
